services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"


  airflow:
    build:
      context: .
      dockerfile: docker/DockerFile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__DEFAULT_TIMEZONE: UTC
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      PYTHONPATH: /opt/airflow
      AIRFLOW_UID: 50000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./api:/opt/airflow/api
      - ./pipeline:/opt/airflow/pipeline
      - ./orchestration:/opt/airflow/orchestration
      - ./ingestion:/opt/airflow/ingestion
      - ./transformations:/opt/airflow/transformations
      - ./storage:/opt/airflow/storage
      - ./utils:/opt/airflow/utils
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./tests:/opt/airflow/tests
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create \
        --username \"${AIRFLOW_ADMIN_USER}\" \ 
        --password \"${AIRFLOW_ADMIN_PASSWORD}\" \ 
        --firstname \"${AIRFLOW_ADMIN_FIRSTNAME}\" \ 
        --lastname \"${AIRFLOW_ADMIN_LASTNAME}\" \
        --role Admin \
        --email \"${AIRFLOW_ADMIN_EMAIL}\" \ || true &&
      airflow webserver
      "

volumes:
  postgres_db: