version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers: 
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO

file:
  class: logging.FileHandler
  formatter: standard
  filename: logs/pipeline.log
  level: DEBUG

loggers:
  pipeline:
    level: DEBUG
    handlers: [console, file]
    propogate: no

root:
  level: INFO
  handlers: [console, file]